# Generated by Django 6.1 on 2026-08-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_notes_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="likes",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
