# Generated by Django 6.1 on 2026-08-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_notes_user_alter_notes_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="public",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
