# Generated by Django 6.1 on 2026-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_notes_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notes",
            name="public",
        ),
        migrations.AddField(
            model_name="notes",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
